# spring.application.name=spring-security

spring:
    config:
        import: optional:file:.env[.properties]
    application:
        name: EquipSync-API
    datasource:
        url: ${DB_URI}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                "[format_sql]": true
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect

auth:
    token:
        jwtSecret: ${JWT_SECRET}
        expirationInMils: ${JWT_EXPIRATION_MS}
    url:
        frontend_url: ${FRONTEND_URL}

server:
    port: 3000

api.prefix: '/api/v1'

# api:
#     prefix: '/api/v1'